# This is a comment

title = "TOML Simple Example"

[server]
    host = "www.example.com"
    port = 80
    time = 123.4
    intA = [ 1, 2, 3, 4, 5]
    dblA = [1.0,2.0,3.0,4.0,5.0]
    bArr = [true, false, true, false, true]
    strA = ["str1", "str2", "str3", "str4", "str__5"]

    enabled = true
