# This is a comment

title = "TOML Simple Example"

[server]

        host = "www.example.com_ǝnlɐʌ‾ǝɯos"
        port = 80
      uptime = 123.4
     enabled = true
        ldt1 = 1979-05-27T07:32:00-05:00
        "키" = "값"
  
    intArray = [ 1, 2, 3, 4, 5]
    dblArray = [1.0,2.0,3.0,4.0,5.0]
   boolArray = [true, false, true, false, true]
    strArray = ["str1", "str2", "str3", "str4", "str__5"]
   dateArray = [2019-01-01, 2019-01-02, 2019-01-03, 2019-01-04, 2019-01-05]
    
      points = [ {x = 1.0, y = 2.0, z = 3.0},
                 {x = 4.0, y = 5.0, z = 6.0},
                 {x = 7.0, y = 8.0, z = 9.0} ]
  
  alt_points = [ [ 1.0, 4.0, 7.0],
                 [ 2.0, 5.0, 8.0],
                 [ 3.0, 6.0, 9.0] ]

