# This is a comment

title = "TOML Simple Example"

[server]
    host = "www.example.com"
    port = 80
    time = 123.4
    intA = [ 1, 2, 3, 4, 5]
    dblA = [1.0,2.0,3.0,4.0,5.0]

    enabled = true
